package com.znc.jd.dao;

import com.znc.jd.dao.util.BaseDao;
import com.znc.jd.domain.JdGoodsAttrval;
import com.znc.jd.domain.JdGoodsAttrvalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JdGoodsAttrvalMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int countByExample(JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByExample(JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insert(JdGoodsAttrval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insertSelective(JdGoodsAttrval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    List<JdGoodsAttrval> selectByExampleWithBLOBs(JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    List<JdGoodsAttrval> selectByExample(JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    JdGoodsAttrval selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") JdGoodsAttrval record, @Param("example") JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") JdGoodsAttrval record, @Param("example") JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExample(@Param("record") JdGoodsAttrval record, @Param("example") JdGoodsAttrvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKeySelective(JdGoodsAttrval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(JdGoodsAttrval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_goods_attrval
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKey(JdGoodsAttrval record);
}