package com.znc.jd.dao;

import com.znc.jd.dao.util.BaseDao;
import com.znc.jd.domain.PProductAttributeValue;
import com.znc.jd.domain.PProductAttributeValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PProductAttributeValueMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int countByExample(PProductAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByExample(PProductAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insert(PProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insertSelective(PProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    List<PProductAttributeValue> selectByExample(PProductAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    PProductAttributeValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") PProductAttributeValue record, @Param("example") PProductAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExample(@Param("record") PProductAttributeValue record, @Param("example") PProductAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKeySelective(PProductAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKey(PProductAttributeValue record);
}