package com.znc.jd.dao;

import com.znc.jd.dao.util.BaseDao;
import com.znc.jd.domain.PShopCategory;
import com.znc.jd.domain.PShopCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PShopCategoryMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int countByExample(PShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByExample(PShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insert(PShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insertSelective(PShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    List<PShopCategory> selectByExample(PShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    PShopCategory selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") PShopCategory record, @Param("example") PShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExample(@Param("record") PShopCategory record, @Param("example") PShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKeySelective(PShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_category
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKey(PShopCategory record);
}