package com.znc.jd.dao;

import com.znc.jd.dao.util.BaseDao;
import com.znc.jd.domain.PShopBrand;
import com.znc.jd.domain.PShopBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PShopBrandMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int countByExample(PShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByExample(PShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int deleteByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insert(PShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int insertSelective(PShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    List<PShopBrand> selectByExample(PShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    PShopBrand selectByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") PShopBrand record, @Param("example") PShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByExample(@Param("record") PShopBrand record, @Param("example") PShopBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKeySelective(PShopBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    int updateByPrimaryKey(PShopBrand record);
}