package com.znc.jd.domain;

import java.io.Serializable;

public class JdCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.parent_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.znke_category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String znkeCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.url
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.level
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_category.path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jd_category
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.id
     *
     * @return the value of jd_category.id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.id
     *
     * @param id the value for jd_category.id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.parent_id
     *
     * @return the value of jd_category.parent_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.parent_id
     *
     * @param parentId the value for jd_category.parent_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.category_name
     *
     * @return the value of jd_category.category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.category_name
     *
     * @param categoryName the value for jd_category.category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.znke_category_name
     *
     * @return the value of jd_category.znke_category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getZnkeCategoryName() {
        return znkeCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.znke_category_name
     *
     * @param znkeCategoryName the value for jd_category.znke_category_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setZnkeCategoryName(String znkeCategoryName) {
        this.znkeCategoryName = znkeCategoryName == null ? null : znkeCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.url
     *
     * @return the value of jd_category.url
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.url
     *
     * @param url the value for jd_category.url
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.level
     *
     * @return the value of jd_category.level
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.level
     *
     * @param level the value for jd_category.level
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_category.path
     *
     * @return the value of jd_category.path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_category.path
     *
     * @param path the value for jd_category.path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}