package com.znc.jd.domain;

import java.io.Serializable;

public class JdGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_title
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_brand
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_box
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_seriel
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsSeriel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.category_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.category_path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String categoryPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.status
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_goods.goods_detail
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private String goodsDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jd_goods
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_id
     *
     * @return the value of jd_goods.goods_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_id
     *
     * @param goodsId the value for jd_goods.goods_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_name
     *
     * @return the value of jd_goods.goods_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_name
     *
     * @param goodsName the value for jd_goods.goods_name
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_title
     *
     * @return the value of jd_goods.goods_title
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_title
     *
     * @param goodsTitle the value for jd_goods.goods_title
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_brand
     *
     * @return the value of jd_goods.goods_brand
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsBrand() {
        return goodsBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_brand
     *
     * @param goodsBrand the value for jd_goods.goods_brand
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsBrand(String goodsBrand) {
        this.goodsBrand = goodsBrand == null ? null : goodsBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_box
     *
     * @return the value of jd_goods.goods_box
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsBox() {
        return goodsBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_box
     *
     * @param goodsBox the value for jd_goods.goods_box
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsBox(String goodsBox) {
        this.goodsBox = goodsBox == null ? null : goodsBox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_seriel
     *
     * @return the value of jd_goods.goods_seriel
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsSeriel() {
        return goodsSeriel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_seriel
     *
     * @param goodsSeriel the value for jd_goods.goods_seriel
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsSeriel(String goodsSeriel) {
        this.goodsSeriel = goodsSeriel == null ? null : goodsSeriel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.category_id
     *
     * @return the value of jd_goods.category_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.category_id
     *
     * @param categoryId the value for jd_goods.category_id
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.category_path
     *
     * @return the value of jd_goods.category_path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getCategoryPath() {
        return categoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.category_path
     *
     * @param categoryPath the value for jd_goods.category_path
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setCategoryPath(String categoryPath) {
        this.categoryPath = categoryPath == null ? null : categoryPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.status
     *
     * @return the value of jd_goods.status
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.status
     *
     * @param status the value for jd_goods.status
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_goods.goods_detail
     *
     * @return the value of jd_goods.goods_detail
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_goods.goods_detail
     *
     * @param goodsDetail the value for jd_goods.goods_detail
     *
     * @mbggenerated Mon Jan 18 10:40:02 CST 2016
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail == null ? null : goodsDetail.trim();
    }
}