package com.znc.jd.domain;

import java.io.Serializable;
import java.util.Date;

public class PProductAttributeValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.pid
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.attribute_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String attributeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String attributeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.classfiy_code
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String classfiyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product_attribute_value.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_product_attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.id
     *
     * @return the value of p_product_attribute_value.id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.id
     *
     * @param id the value for p_product_attribute_value.id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.pid
     *
     * @return the value of p_product_attribute_value.pid
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.pid
     *
     * @param pid the value for p_product_attribute_value.pid
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.attribute_name
     *
     * @return the value of p_product_attribute_value.attribute_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.attribute_name
     *
     * @param attributeName the value for p_product_attribute_value.attribute_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.attribute_value
     *
     * @return the value of p_product_attribute_value.attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.attribute_value
     *
     * @param attributeValue the value for p_product_attribute_value.attribute_value
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.classfiy_code
     *
     * @return the value of p_product_attribute_value.classfiy_code
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getClassfiyCode() {
        return classfiyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.classfiy_code
     *
     * @param classfiyCode the value for p_product_attribute_value.classfiy_code
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setClassfiyCode(String classfiyCode) {
        this.classfiyCode = classfiyCode == null ? null : classfiyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.created_by
     *
     * @return the value of p_product_attribute_value.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.created_by
     *
     * @param createdBy the value for p_product_attribute_value.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.created_by_name
     *
     * @return the value of p_product_attribute_value.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.created_by_name
     *
     * @param createdByName the value for p_product_attribute_value.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.created_time
     *
     * @return the value of p_product_attribute_value.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.created_time
     *
     * @param createdTime the value for p_product_attribute_value.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.modified_by
     *
     * @return the value of p_product_attribute_value.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.modified_by
     *
     * @param modifiedBy the value for p_product_attribute_value.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.modified_by_name
     *
     * @return the value of p_product_attribute_value.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedByName() {
        return modifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.modified_by_name
     *
     * @param modifiedByName the value for p_product_attribute_value.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedByName(String modifiedByName) {
        this.modifiedByName = modifiedByName == null ? null : modifiedByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.modified_time
     *
     * @return the value of p_product_attribute_value.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.modified_time
     *
     * @param modifiedTime the value for p_product_attribute_value.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product_attribute_value.status
     *
     * @return the value of p_product_attribute_value.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product_attribute_value.status
     *
     * @param status the value for p_product_attribute_value.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}