package com.znc.jd.domain;

import java.io.Serializable;
import java.util.Date;

public class PShopBrand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.brand_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.web_url
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.logo_path
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String logoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.priority
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.is_sift
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Byte isSift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.is_disabled
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Byte isDisabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.firstcharacter
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String firstcharacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_brand.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_shop_brand
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.brand_id
     *
     * @return the value of p_shop_brand.brand_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.brand_id
     *
     * @param brandId the value for p_shop_brand.brand_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.name
     *
     * @return the value of p_shop_brand.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.name
     *
     * @param name the value for p_shop_brand.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.alias
     *
     * @return the value of p_shop_brand.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.alias
     *
     * @param alias the value for p_shop_brand.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.web_url
     *
     * @return the value of p_shop_brand.web_url
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.web_url
     *
     * @param webUrl the value for p_shop_brand.web_url
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.logo_path
     *
     * @return the value of p_shop_brand.logo_path
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getLogoPath() {
        return logoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.logo_path
     *
     * @param logoPath the value for p_shop_brand.logo_path
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setLogoPath(String logoPath) {
        this.logoPath = logoPath == null ? null : logoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.priority
     *
     * @return the value of p_shop_brand.priority
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.priority
     *
     * @param priority the value for p_shop_brand.priority
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.is_sift
     *
     * @return the value of p_shop_brand.is_sift
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Byte getIsSift() {
        return isSift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.is_sift
     *
     * @param isSift the value for p_shop_brand.is_sift
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setIsSift(Byte isSift) {
        this.isSift = isSift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.is_disabled
     *
     * @return the value of p_shop_brand.is_disabled
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Byte getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.is_disabled
     *
     * @param isDisabled the value for p_shop_brand.is_disabled
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setIsDisabled(Byte isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.firstcharacter
     *
     * @return the value of p_shop_brand.firstcharacter
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getFirstcharacter() {
        return firstcharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.firstcharacter
     *
     * @param firstcharacter the value for p_shop_brand.firstcharacter
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setFirstcharacter(String firstcharacter) {
        this.firstcharacter = firstcharacter == null ? null : firstcharacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.created_by
     *
     * @return the value of p_shop_brand.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.created_by
     *
     * @param createdBy the value for p_shop_brand.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.created_by_name
     *
     * @return the value of p_shop_brand.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.created_by_name
     *
     * @param createdByName the value for p_shop_brand.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.created_time
     *
     * @return the value of p_shop_brand.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.created_time
     *
     * @param createdTime the value for p_shop_brand.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.modified_by
     *
     * @return the value of p_shop_brand.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.modified_by
     *
     * @param modifiedBy the value for p_shop_brand.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.modified_by_name
     *
     * @return the value of p_shop_brand.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedByName() {
        return modifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.modified_by_name
     *
     * @param modifiedByName the value for p_shop_brand.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedByName(String modifiedByName) {
        this.modifiedByName = modifiedByName == null ? null : modifiedByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_brand.modified_time
     *
     * @return the value of p_shop_brand.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_brand.modified_time
     *
     * @param modifiedTime the value for p_shop_brand.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}