package com.znc.jd.domain;

import java.io.Serializable;
import java.util.Date;

public class PShopPtype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.ptype_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Long ptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String modifiedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_shop_ptype.props
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private String props;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_shop_ptype
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.ptype_id
     *
     * @return the value of p_shop_ptype.ptype_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Long getPtypeId() {
        return ptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.ptype_id
     *
     * @param ptypeId the value for p_shop_ptype.ptype_id
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setPtypeId(Long ptypeId) {
        this.ptypeId = ptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.name
     *
     * @return the value of p_shop_ptype.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.name
     *
     * @param name the value for p_shop_ptype.name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.alias
     *
     * @return the value of p_shop_ptype.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.alias
     *
     * @param alias the value for p_shop_ptype.alias
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.created_by
     *
     * @return the value of p_shop_ptype.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.created_by
     *
     * @param createdBy the value for p_shop_ptype.created_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.created_by_name
     *
     * @return the value of p_shop_ptype.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.created_by_name
     *
     * @param createdByName the value for p_shop_ptype.created_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.created_time
     *
     * @return the value of p_shop_ptype.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.created_time
     *
     * @param createdTime the value for p_shop_ptype.created_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.modified_by
     *
     * @return the value of p_shop_ptype.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.modified_by
     *
     * @param modifiedBy the value for p_shop_ptype.modified_by
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.modified_by_name
     *
     * @return the value of p_shop_ptype.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getModifiedByName() {
        return modifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.modified_by_name
     *
     * @param modifiedByName the value for p_shop_ptype.modified_by_name
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedByName(String modifiedByName) {
        this.modifiedByName = modifiedByName == null ? null : modifiedByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.modified_time
     *
     * @return the value of p_shop_ptype.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.modified_time
     *
     * @param modifiedTime the value for p_shop_ptype.modified_time
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.status
     *
     * @return the value of p_shop_ptype.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.status
     *
     * @param status the value for p_shop_ptype.status
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_shop_ptype.props
     *
     * @return the value of p_shop_ptype.props
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public String getProps() {
        return props;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_shop_ptype.props
     *
     * @param props the value for p_shop_ptype.props
     *
     * @mbggenerated Mon Jan 18 10:40:03 CST 2016
     */
    public void setProps(String props) {
        this.props = props == null ? null : props.trim();
    }
}