package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductMobile;
import com.znc.mycrawler.domain.ProductMobileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMobileMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductMobile> selectByExample(ProductMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductMobile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductMobile record, @Param("example") ProductMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductMobile record, @Param("example") ProductMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductMobile record);
}