package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductMobileAccessory;
import com.znc.mycrawler.domain.ProductMobileAccessoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMobileAccessoryMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductMobileAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductMobileAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductMobileAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductMobileAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductMobileAccessory> selectByExample(ProductMobileAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductMobileAccessory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductMobileAccessory record, @Param("example") ProductMobileAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductMobileAccessory record, @Param("example") ProductMobileAccessoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductMobileAccessory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_mobile_accessory
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductMobileAccessory record);
}