package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductModelImage;
import com.znc.mycrawler.domain.ProductModelImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductModelImageMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductModelImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductModelImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductModelImage> selectByExample(ProductModelImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductModelImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductModelImage record, @Param("example") ProductModelImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductModelImage record, @Param("example") ProductModelImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductModelImage record);
}