package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductModelExtraAttr;
import com.znc.mycrawler.domain.ProductModelExtraAttrExample;
import com.znc.mycrawler.domain.ProductModelExtraAttrWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductModelExtraAttrMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductModelExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductModelExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductModelExtraAttrWithBLOBs> selectByExampleWithBLOBs(ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductModelExtraAttr> selectByExample(ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductModelExtraAttrWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductModelExtraAttrWithBLOBs record, @Param("example") ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ProductModelExtraAttrWithBLOBs record, @Param("example") ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductModelExtraAttr record, @Param("example") ProductModelExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductModelExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ProductModelExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductModelExtraAttr record);
}