package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductTitleImage;
import com.znc.mycrawler.domain.ProductTitleImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTitleImageMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductTitleImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductTitleImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductTitleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductTitleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductTitleImage> selectByExample(ProductTitleImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductTitleImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductTitleImage record, @Param("example") ProductTitleImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductTitleImage record, @Param("example") ProductTitleImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductTitleImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_title_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductTitleImage record);
}