package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductExtraAttr;
import com.znc.mycrawler.domain.ProductExtraAttrExample;
import com.znc.mycrawler.domain.ProductExtraAttrWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductExtraAttrMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductExtraAttrWithBLOBs> selectByExampleWithBLOBs(ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductExtraAttr> selectByExample(ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductExtraAttrWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductExtraAttrWithBLOBs record, @Param("example") ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ProductExtraAttrWithBLOBs record, @Param("example") ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductExtraAttr record, @Param("example") ProductExtraAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ProductExtraAttrWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductExtraAttr record);
}