package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.ProductPad;
import com.znc.mycrawler.domain.ProductPadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPadMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(ProductPadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(ProductPadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(ProductPad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(ProductPad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<ProductPad> selectByExample(ProductPadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    ProductPad selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductPad record, @Param("example") ProductPadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") ProductPad record, @Param("example") ProductPadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProductPad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(ProductPad record);
}