package com.znc.mycrawler.dao;

import com.znc.mycrawler.dao.util.BaseDao;
import com.znc.mycrawler.domain.SalesProperties;
import com.znc.mycrawler.domain.SalesPropertiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesPropertiesMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int countByExample(SalesPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByExample(SalesPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insert(SalesProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int insertSelective(SalesProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    List<SalesProperties> selectByExample(SalesPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    SalesProperties selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") SalesProperties record, @Param("example") SalesPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByExample(@Param("record") SalesProperties record, @Param("example") SalesPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKeySelective(SalesProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_properties
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    int updateByPrimaryKey(SalesProperties record);
}