package com.znc.mycrawler.domain;

import java.io.Serializable;

public class ProductImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.image_url
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_image
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.id
     *
     * @return the value of product_image.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.id
     *
     * @param id the value for product_image.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.pid
     *
     * @return the value of product_image.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.pid
     *
     * @param pid the value for product_image.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.image_url
     *
     * @return the value of product_image.image_url
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.image_url
     *
     * @param imageUrl the value for product_image.image_url
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}