package com.znc.mycrawler.domain;

import java.io.Serializable;

public class ProductMobile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String marketsoldTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.outward
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String outward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.intelligent
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String intelligent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.systemversion
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String systemversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuCore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.mobile_oper
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String mobileOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.mobile_os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String mobileOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.wait_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String waitModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.operator_mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String operatorMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.sim
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String sim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.fourg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String fourg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String threeg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.twog
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String twog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.mobile_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String mobileModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.network
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String network;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String localmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.runmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String runmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.store_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String storeModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String maxmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.screen_texture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenTexture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenResolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.screen_color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String gravity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String light;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.distance
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.gyroscope
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String gyroscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.compass
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String compass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.superfont
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String superfont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.video_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String videoPixel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.subvideo_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String subvideoPixel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.flashlight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String flashlight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.sensor_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String sensorModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.focal_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String focalModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.auto_focal
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String autoFocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.take_picture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String takePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String buletooth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String battery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.change_battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String changeBattery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.person_help
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String personHelp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String outSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.eraphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String eraphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.data_light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String dataLight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.data_business
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String dataBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.ccc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String ccc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.pc_syc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pcSyc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.threed
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String threed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.nfc_trans
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String nfcTrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String wifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.person_hot
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String personHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String standbyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.talk_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String talkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Integer drawenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Long classfiyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String suningNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_mobile.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_mobile
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.id
     *
     * @return the value of product_mobile.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.id
     *
     * @param id the value for product_mobile.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.brand
     *
     * @return the value of product_mobile.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.brand
     *
     * @param brand the value for product_mobile.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.pmodel
     *
     * @return the value of product_mobile.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPmodel() {
        return pmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.pmodel
     *
     * @param pmodel the value for product_mobile.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPmodel(String pmodel) {
        this.pmodel = pmodel == null ? null : pmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.marketsold_time
     *
     * @return the value of product_mobile.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMarketsoldTime() {
        return marketsoldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.marketsold_time
     *
     * @param marketsoldTime the value for product_mobile.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMarketsoldTime(String marketsoldTime) {
        this.marketsoldTime = marketsoldTime == null ? null : marketsoldTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.outward
     *
     * @return the value of product_mobile.outward
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getOutward() {
        return outward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.outward
     *
     * @param outward the value for product_mobile.outward
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setOutward(String outward) {
        this.outward = outward == null ? null : outward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.color
     *
     * @return the value of product_mobile.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.color
     *
     * @param color the value for product_mobile.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.intelligent
     *
     * @return the value of product_mobile.intelligent
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getIntelligent() {
        return intelligent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.intelligent
     *
     * @param intelligent the value for product_mobile.intelligent
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setIntelligent(String intelligent) {
        this.intelligent = intelligent == null ? null : intelligent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.systemversion
     *
     * @return the value of product_mobile.systemversion
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSystemversion() {
        return systemversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.systemversion
     *
     * @param systemversion the value for product_mobile.systemversion
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSystemversion(String systemversion) {
        this.systemversion = systemversion == null ? null : systemversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.cpu_model
     *
     * @return the value of product_mobile.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuModel() {
        return cpuModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.cpu_model
     *
     * @param cpuModel the value for product_mobile.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuModel(String cpuModel) {
        this.cpuModel = cpuModel == null ? null : cpuModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.cpu_frequency
     *
     * @return the value of product_mobile.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuFrequency() {
        return cpuFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.cpu_frequency
     *
     * @param cpuFrequency the value for product_mobile.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuFrequency(String cpuFrequency) {
        this.cpuFrequency = cpuFrequency == null ? null : cpuFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.cpu_core
     *
     * @return the value of product_mobile.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuCore() {
        return cpuCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.cpu_core
     *
     * @param cpuCore the value for product_mobile.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuCore(String cpuCore) {
        this.cpuCore = cpuCore == null ? null : cpuCore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.mobile_oper
     *
     * @return the value of product_mobile.mobile_oper
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMobileOper() {
        return mobileOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.mobile_oper
     *
     * @param mobileOper the value for product_mobile.mobile_oper
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMobileOper(String mobileOper) {
        this.mobileOper = mobileOper == null ? null : mobileOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.mobile_os
     *
     * @return the value of product_mobile.mobile_os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMobileOs() {
        return mobileOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.mobile_os
     *
     * @param mobileOs the value for product_mobile.mobile_os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMobileOs(String mobileOs) {
        this.mobileOs = mobileOs == null ? null : mobileOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.wait_model
     *
     * @return the value of product_mobile.wait_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWaitModel() {
        return waitModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.wait_model
     *
     * @param waitModel the value for product_mobile.wait_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWaitModel(String waitModel) {
        this.waitModel = waitModel == null ? null : waitModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.operator_mark
     *
     * @return the value of product_mobile.operator_mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getOperatorMark() {
        return operatorMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.operator_mark
     *
     * @param operatorMark the value for product_mobile.operator_mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setOperatorMark(String operatorMark) {
        this.operatorMark = operatorMark == null ? null : operatorMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.sim
     *
     * @return the value of product_mobile.sim
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSim() {
        return sim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.sim
     *
     * @param sim the value for product_mobile.sim
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSim(String sim) {
        this.sim = sim == null ? null : sim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.video
     *
     * @return the value of product_mobile.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.video
     *
     * @param video the value for product_mobile.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.fourg
     *
     * @return the value of product_mobile.fourg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getFourg() {
        return fourg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.fourg
     *
     * @param fourg the value for product_mobile.fourg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setFourg(String fourg) {
        this.fourg = fourg == null ? null : fourg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.threeg
     *
     * @return the value of product_mobile.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getThreeg() {
        return threeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.threeg
     *
     * @param threeg the value for product_mobile.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setThreeg(String threeg) {
        this.threeg = threeg == null ? null : threeg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.twog
     *
     * @return the value of product_mobile.twog
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getTwog() {
        return twog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.twog
     *
     * @param twog the value for product_mobile.twog
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setTwog(String twog) {
        this.twog = twog == null ? null : twog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.mobile_model
     *
     * @return the value of product_mobile.mobile_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMobileModel() {
        return mobileModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.mobile_model
     *
     * @param mobileModel the value for product_mobile.mobile_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMobileModel(String mobileModel) {
        this.mobileModel = mobileModel == null ? null : mobileModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.network
     *
     * @return the value of product_mobile.network
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getNetwork() {
        return network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.network
     *
     * @param network the value for product_mobile.network
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setNetwork(String network) {
        this.network = network == null ? null : network.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.localmen
     *
     * @return the value of product_mobile.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getLocalmen() {
        return localmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.localmen
     *
     * @param localmen the value for product_mobile.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setLocalmen(String localmen) {
        this.localmen = localmen == null ? null : localmen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.runmen
     *
     * @return the value of product_mobile.runmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getRunmen() {
        return runmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.runmen
     *
     * @param runmen the value for product_mobile.runmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setRunmen(String runmen) {
        this.runmen = runmen == null ? null : runmen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.store_model
     *
     * @return the value of product_mobile.store_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getStoreModel() {
        return storeModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.store_model
     *
     * @param storeModel the value for product_mobile.store_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setStoreModel(String storeModel) {
        this.storeModel = storeModel == null ? null : storeModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.maxmen
     *
     * @return the value of product_mobile.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMaxmen() {
        return maxmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.maxmen
     *
     * @param maxmen the value for product_mobile.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMaxmen(String maxmen) {
        this.maxmen = maxmen == null ? null : maxmen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.screen_texture
     *
     * @return the value of product_mobile.screen_texture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenTexture() {
        return screenTexture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.screen_texture
     *
     * @param screenTexture the value for product_mobile.screen_texture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenTexture(String screenTexture) {
        this.screenTexture = screenTexture == null ? null : screenTexture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.screen_size
     *
     * @return the value of product_mobile.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenSize() {
        return screenSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.screen_size
     *
     * @param screenSize the value for product_mobile.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize == null ? null : screenSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.screen_resolution
     *
     * @return the value of product_mobile.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenResolution() {
        return screenResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.screen_resolution
     *
     * @param screenResolution the value for product_mobile.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenResolution(String screenResolution) {
        this.screenResolution = screenResolution == null ? null : screenResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.screen_color
     *
     * @return the value of product_mobile.screen_color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenColor() {
        return screenColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.screen_color
     *
     * @param screenColor the value for product_mobile.screen_color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenColor(String screenColor) {
        this.screenColor = screenColor == null ? null : screenColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.gravity
     *
     * @return the value of product_mobile.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.gravity
     *
     * @param gravity the value for product_mobile.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setGravity(String gravity) {
        this.gravity = gravity == null ? null : gravity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.light
     *
     * @return the value of product_mobile.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getLight() {
        return light;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.light
     *
     * @param light the value for product_mobile.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setLight(String light) {
        this.light = light == null ? null : light.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.distance
     *
     * @return the value of product_mobile.distance
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.distance
     *
     * @param distance the value for product_mobile.distance
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setDistance(String distance) {
        this.distance = distance == null ? null : distance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.gyroscope
     *
     * @return the value of product_mobile.gyroscope
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getGyroscope() {
        return gyroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.gyroscope
     *
     * @param gyroscope the value for product_mobile.gyroscope
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setGyroscope(String gyroscope) {
        this.gyroscope = gyroscope == null ? null : gyroscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.compass
     *
     * @return the value of product_mobile.compass
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCompass() {
        return compass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.compass
     *
     * @param compass the value for product_mobile.compass
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCompass(String compass) {
        this.compass = compass == null ? null : compass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.superfont
     *
     * @return the value of product_mobile.superfont
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSuperfont() {
        return superfont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.superfont
     *
     * @param superfont the value for product_mobile.superfont
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSuperfont(String superfont) {
        this.superfont = superfont == null ? null : superfont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.video_pixel
     *
     * @return the value of product_mobile.video_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getVideoPixel() {
        return videoPixel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.video_pixel
     *
     * @param videoPixel the value for product_mobile.video_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setVideoPixel(String videoPixel) {
        this.videoPixel = videoPixel == null ? null : videoPixel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.subvideo_pixel
     *
     * @return the value of product_mobile.subvideo_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSubvideoPixel() {
        return subvideoPixel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.subvideo_pixel
     *
     * @param subvideoPixel the value for product_mobile.subvideo_pixel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSubvideoPixel(String subvideoPixel) {
        this.subvideoPixel = subvideoPixel == null ? null : subvideoPixel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.flashlight
     *
     * @return the value of product_mobile.flashlight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getFlashlight() {
        return flashlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.flashlight
     *
     * @param flashlight the value for product_mobile.flashlight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setFlashlight(String flashlight) {
        this.flashlight = flashlight == null ? null : flashlight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.sensor_model
     *
     * @return the value of product_mobile.sensor_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSensorModel() {
        return sensorModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.sensor_model
     *
     * @param sensorModel the value for product_mobile.sensor_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSensorModel(String sensorModel) {
        this.sensorModel = sensorModel == null ? null : sensorModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.focal_model
     *
     * @return the value of product_mobile.focal_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getFocalModel() {
        return focalModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.focal_model
     *
     * @param focalModel the value for product_mobile.focal_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setFocalModel(String focalModel) {
        this.focalModel = focalModel == null ? null : focalModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.auto_focal
     *
     * @return the value of product_mobile.auto_focal
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getAutoFocal() {
        return autoFocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.auto_focal
     *
     * @param autoFocal the value for product_mobile.auto_focal
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setAutoFocal(String autoFocal) {
        this.autoFocal = autoFocal == null ? null : autoFocal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.take_picture
     *
     * @return the value of product_mobile.take_picture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getTakePicture() {
        return takePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.take_picture
     *
     * @param takePicture the value for product_mobile.take_picture
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setTakePicture(String takePicture) {
        this.takePicture = takePicture == null ? null : takePicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.buletooth
     *
     * @return the value of product_mobile.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBuletooth() {
        return buletooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.buletooth
     *
     * @param buletooth the value for product_mobile.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBuletooth(String buletooth) {
        this.buletooth = buletooth == null ? null : buletooth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.battery
     *
     * @return the value of product_mobile.battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBattery() {
        return battery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.battery
     *
     * @param battery the value for product_mobile.battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBattery(String battery) {
        this.battery = battery == null ? null : battery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.change_battery
     *
     * @return the value of product_mobile.change_battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getChangeBattery() {
        return changeBattery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.change_battery
     *
     * @param changeBattery the value for product_mobile.change_battery
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setChangeBattery(String changeBattery) {
        this.changeBattery = changeBattery == null ? null : changeBattery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.person_help
     *
     * @return the value of product_mobile.person_help
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPersonHelp() {
        return personHelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.person_help
     *
     * @param personHelp the value for product_mobile.person_help
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPersonHelp(String personHelp) {
        this.personHelp = personHelp == null ? null : personHelp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.out_size
     *
     * @return the value of product_mobile.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getOutSize() {
        return outSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.out_size
     *
     * @param outSize the value for product_mobile.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setOutSize(String outSize) {
        this.outSize = outSize == null ? null : outSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.weight
     *
     * @return the value of product_mobile.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.weight
     *
     * @param weight the value for product_mobile.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.eraphone
     *
     * @return the value of product_mobile.eraphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getEraphone() {
        return eraphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.eraphone
     *
     * @param eraphone the value for product_mobile.eraphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setEraphone(String eraphone) {
        this.eraphone = eraphone == null ? null : eraphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.data_light
     *
     * @return the value of product_mobile.data_light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getDataLight() {
        return dataLight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.data_light
     *
     * @param dataLight the value for product_mobile.data_light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setDataLight(String dataLight) {
        this.dataLight = dataLight == null ? null : dataLight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.data_business
     *
     * @return the value of product_mobile.data_business
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getDataBusiness() {
        return dataBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.data_business
     *
     * @param dataBusiness the value for product_mobile.data_business
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setDataBusiness(String dataBusiness) {
        this.dataBusiness = dataBusiness == null ? null : dataBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.ccc
     *
     * @return the value of product_mobile.ccc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCcc() {
        return ccc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.ccc
     *
     * @param ccc the value for product_mobile.ccc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCcc(String ccc) {
        this.ccc = ccc == null ? null : ccc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.pc_syc
     *
     * @return the value of product_mobile.pc_syc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPcSyc() {
        return pcSyc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.pc_syc
     *
     * @param pcSyc the value for product_mobile.pc_syc
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPcSyc(String pcSyc) {
        this.pcSyc = pcSyc == null ? null : pcSyc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.threed
     *
     * @return the value of product_mobile.threed
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getThreed() {
        return threed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.threed
     *
     * @param threed the value for product_mobile.threed
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setThreed(String threed) {
        this.threed = threed == null ? null : threed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.nfc_trans
     *
     * @return the value of product_mobile.nfc_trans
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getNfcTrans() {
        return nfcTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.nfc_trans
     *
     * @param nfcTrans the value for product_mobile.nfc_trans
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setNfcTrans(String nfcTrans) {
        this.nfcTrans = nfcTrans == null ? null : nfcTrans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.wifi
     *
     * @return the value of product_mobile.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWifi() {
        return wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.wifi
     *
     * @param wifi the value for product_mobile.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWifi(String wifi) {
        this.wifi = wifi == null ? null : wifi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.person_hot
     *
     * @return the value of product_mobile.person_hot
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPersonHot() {
        return personHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.person_hot
     *
     * @param personHot the value for product_mobile.person_hot
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPersonHot(String personHot) {
        this.personHot = personHot == null ? null : personHot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.gps
     *
     * @return the value of product_mobile.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.gps
     *
     * @param gps the value for product_mobile.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.standby_time
     *
     * @return the value of product_mobile.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getStandbyTime() {
        return standbyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.standby_time
     *
     * @param standbyTime the value for product_mobile.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setStandbyTime(String standbyTime) {
        this.standbyTime = standbyTime == null ? null : standbyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.talk_time
     *
     * @return the value of product_mobile.talk_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getTalkTime() {
        return talkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.talk_time
     *
     * @param talkTime the value for product_mobile.talk_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setTalkTime(String talkTime) {
        this.talkTime = talkTime == null ? null : talkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.drawenable
     *
     * @return the value of product_mobile.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Integer getDrawenable() {
        return drawenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.drawenable
     *
     * @param drawenable the value for product_mobile.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setDrawenable(Integer drawenable) {
        this.drawenable = drawenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.classfiy_code
     *
     * @return the value of product_mobile.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Long getClassfiyCode() {
        return classfiyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.classfiy_code
     *
     * @param classfiyCode the value for product_mobile.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setClassfiyCode(Long classfiyCode) {
        this.classfiyCode = classfiyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.suning_number
     *
     * @return the value of product_mobile.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSuningNumber() {
        return suningNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.suning_number
     *
     * @param suningNumber the value for product_mobile.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSuningNumber(String suningNumber) {
        this.suningNumber = suningNumber == null ? null : suningNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_mobile.product_name
     *
     * @return the value of product_mobile.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_mobile.product_name
     *
     * @param productName the value for product_mobile.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }
}