package com.znc.mycrawler.domain;

import java.io.Serializable;

public class ProductClassfiy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.cid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.iconUrl
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String iconurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.pcode
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_classfiy.level
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_classfiy
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.cid
     *
     * @return the value of product_classfiy.cid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.cid
     *
     * @param cid the value for product_classfiy.cid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.code
     *
     * @return the value of product_classfiy.code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.code
     *
     * @param code the value for product_classfiy.code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.name
     *
     * @return the value of product_classfiy.name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.name
     *
     * @param name the value for product_classfiy.name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.iconUrl
     *
     * @return the value of product_classfiy.iconUrl
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getIconurl() {
        return iconurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.iconUrl
     *
     * @param iconurl the value for product_classfiy.iconUrl
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl == null ? null : iconurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.pcode
     *
     * @return the value of product_classfiy.pcode
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.pcode
     *
     * @param pcode the value for product_classfiy.pcode
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.mark
     *
     * @return the value of product_classfiy.mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.mark
     *
     * @param mark the value for product_classfiy.mark
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_classfiy.level
     *
     * @return the value of product_classfiy.level
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_classfiy.level
     *
     * @param level the value for product_classfiy.level
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}