package com.znc.mycrawler.domain;

import java.io.Serializable;

public class ProductExtraAttr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_extra_attr.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_extra_attr.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_extra_attr
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_extra_attr.id
     *
     * @return the value of product_extra_attr.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_extra_attr.id
     *
     * @param id the value for product_extra_attr.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_extra_attr.pid
     *
     * @return the value of product_extra_attr.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_extra_attr.pid
     *
     * @param pid the value for product_extra_attr.pid
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}