package com.znc.mycrawler.domain;

import java.io.Serializable;

public class ProductPad implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String pmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String marketsoldTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.storage_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String storageCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuCore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String cpuFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String localmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String maxmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenResolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.screen_scale
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.screen_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String screenModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String wifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String buletooth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.audio_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String audioPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.usb_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String usbPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.speakers
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String speakers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.microphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String microphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.flash
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String flash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String light;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String gravity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.battery_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String batteryModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.battery_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String batteryCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String standbyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String outSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.warranty_policy
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String warrantyPolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.call_function
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String callFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String threeg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.multipoint
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String multipoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.video_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String videoPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private Integer drawenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String classfiyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pad.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private String suningNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_pad
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.id
     *
     * @return the value of product_pad.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.id
     *
     * @param id the value for product_pad.id
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.brand
     *
     * @return the value of product_pad.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.brand
     *
     * @param brand the value for product_pad.brand
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.pmodel
     *
     * @return the value of product_pad.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getPmodel() {
        return pmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.pmodel
     *
     * @param pmodel the value for product_pad.pmodel
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setPmodel(String pmodel) {
        this.pmodel = pmodel == null ? null : pmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.product_name
     *
     * @return the value of product_pad.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.product_name
     *
     * @param productName the value for product_pad.product_name
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.color
     *
     * @return the value of product_pad.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.color
     *
     * @param color the value for product_pad.color
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.marketsold_time
     *
     * @return the value of product_pad.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMarketsoldTime() {
        return marketsoldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.marketsold_time
     *
     * @param marketsoldTime the value for product_pad.marketsold_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMarketsoldTime(String marketsoldTime) {
        this.marketsoldTime = marketsoldTime == null ? null : marketsoldTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.storage_capacity
     *
     * @return the value of product_pad.storage_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getStorageCapacity() {
        return storageCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.storage_capacity
     *
     * @param storageCapacity the value for product_pad.storage_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setStorageCapacity(String storageCapacity) {
        this.storageCapacity = storageCapacity == null ? null : storageCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.os
     *
     * @return the value of product_pad.os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.os
     *
     * @param os the value for product_pad.os
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.cpu_core
     *
     * @return the value of product_pad.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuCore() {
        return cpuCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.cpu_core
     *
     * @param cpuCore the value for product_pad.cpu_core
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuCore(String cpuCore) {
        this.cpuCore = cpuCore == null ? null : cpuCore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.cpu_model
     *
     * @return the value of product_pad.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuModel() {
        return cpuModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.cpu_model
     *
     * @param cpuModel the value for product_pad.cpu_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuModel(String cpuModel) {
        this.cpuModel = cpuModel == null ? null : cpuModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.cpu_frequency
     *
     * @return the value of product_pad.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCpuFrequency() {
        return cpuFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.cpu_frequency
     *
     * @param cpuFrequency the value for product_pad.cpu_frequency
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCpuFrequency(String cpuFrequency) {
        this.cpuFrequency = cpuFrequency == null ? null : cpuFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.localmen
     *
     * @return the value of product_pad.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getLocalmen() {
        return localmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.localmen
     *
     * @param localmen the value for product_pad.localmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setLocalmen(String localmen) {
        this.localmen = localmen == null ? null : localmen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.maxmen
     *
     * @return the value of product_pad.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMaxmen() {
        return maxmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.maxmen
     *
     * @param maxmen the value for product_pad.maxmen
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMaxmen(String maxmen) {
        this.maxmen = maxmen == null ? null : maxmen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.screen_size
     *
     * @return the value of product_pad.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenSize() {
        return screenSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.screen_size
     *
     * @param screenSize the value for product_pad.screen_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize == null ? null : screenSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.screen_resolution
     *
     * @return the value of product_pad.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenResolution() {
        return screenResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.screen_resolution
     *
     * @param screenResolution the value for product_pad.screen_resolution
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenResolution(String screenResolution) {
        this.screenResolution = screenResolution == null ? null : screenResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.screen_scale
     *
     * @return the value of product_pad.screen_scale
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenScale() {
        return screenScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.screen_scale
     *
     * @param screenScale the value for product_pad.screen_scale
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenScale(String screenScale) {
        this.screenScale = screenScale == null ? null : screenScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.screen_model
     *
     * @return the value of product_pad.screen_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getScreenModel() {
        return screenModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.screen_model
     *
     * @param screenModel the value for product_pad.screen_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setScreenModel(String screenModel) {
        this.screenModel = screenModel == null ? null : screenModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.wifi
     *
     * @return the value of product_pad.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWifi() {
        return wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.wifi
     *
     * @param wifi the value for product_pad.wifi
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWifi(String wifi) {
        this.wifi = wifi == null ? null : wifi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.buletooth
     *
     * @return the value of product_pad.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBuletooth() {
        return buletooth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.buletooth
     *
     * @param buletooth the value for product_pad.buletooth
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBuletooth(String buletooth) {
        this.buletooth = buletooth == null ? null : buletooth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.audio_port
     *
     * @return the value of product_pad.audio_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getAudioPort() {
        return audioPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.audio_port
     *
     * @param audioPort the value for product_pad.audio_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setAudioPort(String audioPort) {
        this.audioPort = audioPort == null ? null : audioPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.usb_port
     *
     * @return the value of product_pad.usb_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getUsbPort() {
        return usbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.usb_port
     *
     * @param usbPort the value for product_pad.usb_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setUsbPort(String usbPort) {
        this.usbPort = usbPort == null ? null : usbPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.speakers
     *
     * @return the value of product_pad.speakers
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSpeakers() {
        return speakers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.speakers
     *
     * @param speakers the value for product_pad.speakers
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSpeakers(String speakers) {
        this.speakers = speakers == null ? null : speakers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.microphone
     *
     * @return the value of product_pad.microphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMicrophone() {
        return microphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.microphone
     *
     * @param microphone the value for product_pad.microphone
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMicrophone(String microphone) {
        this.microphone = microphone == null ? null : microphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.video
     *
     * @return the value of product_pad.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.video
     *
     * @param video the value for product_pad.video
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.flash
     *
     * @return the value of product_pad.flash
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getFlash() {
        return flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.flash
     *
     * @param flash the value for product_pad.flash
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setFlash(String flash) {
        this.flash = flash == null ? null : flash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.light
     *
     * @return the value of product_pad.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getLight() {
        return light;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.light
     *
     * @param light the value for product_pad.light
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setLight(String light) {
        this.light = light == null ? null : light.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.gravity
     *
     * @return the value of product_pad.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.gravity
     *
     * @param gravity the value for product_pad.gravity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setGravity(String gravity) {
        this.gravity = gravity == null ? null : gravity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.gps
     *
     * @return the value of product_pad.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.gps
     *
     * @param gps the value for product_pad.gps
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.battery_model
     *
     * @return the value of product_pad.battery_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBatteryModel() {
        return batteryModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.battery_model
     *
     * @param batteryModel the value for product_pad.battery_model
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBatteryModel(String batteryModel) {
        this.batteryModel = batteryModel == null ? null : batteryModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.battery_capacity
     *
     * @return the value of product_pad.battery_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getBatteryCapacity() {
        return batteryCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.battery_capacity
     *
     * @param batteryCapacity the value for product_pad.battery_capacity
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setBatteryCapacity(String batteryCapacity) {
        this.batteryCapacity = batteryCapacity == null ? null : batteryCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.standby_time
     *
     * @return the value of product_pad.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getStandbyTime() {
        return standbyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.standby_time
     *
     * @param standbyTime the value for product_pad.standby_time
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setStandbyTime(String standbyTime) {
        this.standbyTime = standbyTime == null ? null : standbyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.out_size
     *
     * @return the value of product_pad.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getOutSize() {
        return outSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.out_size
     *
     * @param outSize the value for product_pad.out_size
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setOutSize(String outSize) {
        this.outSize = outSize == null ? null : outSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.weight
     *
     * @return the value of product_pad.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.weight
     *
     * @param weight the value for product_pad.weight
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.warranty_policy
     *
     * @return the value of product_pad.warranty_policy
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getWarrantyPolicy() {
        return warrantyPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.warranty_policy
     *
     * @param warrantyPolicy the value for product_pad.warranty_policy
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setWarrantyPolicy(String warrantyPolicy) {
        this.warrantyPolicy = warrantyPolicy == null ? null : warrantyPolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.call_function
     *
     * @return the value of product_pad.call_function
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getCallFunction() {
        return callFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.call_function
     *
     * @param callFunction the value for product_pad.call_function
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setCallFunction(String callFunction) {
        this.callFunction = callFunction == null ? null : callFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.threeg
     *
     * @return the value of product_pad.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getThreeg() {
        return threeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.threeg
     *
     * @param threeg the value for product_pad.threeg
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setThreeg(String threeg) {
        this.threeg = threeg == null ? null : threeg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.multipoint
     *
     * @return the value of product_pad.multipoint
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getMultipoint() {
        return multipoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.multipoint
     *
     * @param multipoint the value for product_pad.multipoint
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setMultipoint(String multipoint) {
        this.multipoint = multipoint == null ? null : multipoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.video_port
     *
     * @return the value of product_pad.video_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getVideoPort() {
        return videoPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.video_port
     *
     * @param videoPort the value for product_pad.video_port
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setVideoPort(String videoPort) {
        this.videoPort = videoPort == null ? null : videoPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.drawenable
     *
     * @return the value of product_pad.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public Integer getDrawenable() {
        return drawenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.drawenable
     *
     * @param drawenable the value for product_pad.drawenable
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setDrawenable(Integer drawenable) {
        this.drawenable = drawenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.classfiy_code
     *
     * @return the value of product_pad.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getClassfiyCode() {
        return classfiyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.classfiy_code
     *
     * @param classfiyCode the value for product_pad.classfiy_code
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setClassfiyCode(String classfiyCode) {
        this.classfiyCode = classfiyCode == null ? null : classfiyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pad.suning_number
     *
     * @return the value of product_pad.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public String getSuningNumber() {
        return suningNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pad.suning_number
     *
     * @param suningNumber the value for product_pad.suning_number
     *
     * @mbggenerated Sat Apr 25 13:33:15 CST 2015
     */
    public void setSuningNumber(String suningNumber) {
        this.suningNumber = suningNumber == null ? null : suningNumber.trim();
    }
}